#server配置
server:
  port: 9001
#数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.107.183.233:3306/blog?useAffectedRows=true&useSSL=false
    password: 654321
    username: root
  messages:
    basename: error
    # mail
  #Redis
  redis:
    host: 47.107.183.233
    port: 6379
    password: 123456
  #mail
  mail:
    host: smtp.qq.com
    username: 1143109382@qq.com
    password: qvsyhvkampifjhif
    properties:
      mail:
        stmp:
          auth: true


mail.address: 1143109382@qq.com