#server配置
server:
  port: 9001
#数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.107.183.233:3306/blog?useUnicode=true&amp&characterEncoding=utf-8
    password: 654321
    username: root
  messages:
    basename: error
    # address
  #Redis
  redis:
    host: 47.107.183.233
    port: 6379
    password: 123456
  #address
  mail:
    host: smtp.qq.com
    username: 1143109382@qq.com
    password: qvsyhvkampifjhif
    properties:
      mail:
        stmp:
          auth: true

#邮箱注册验证码模板
mail:
  address: 1143109382@qq.com
  verify:
    code:
      template: 您的验证码为【%s】

aliyun.AccessKey.id: LTAI4FxhgFHyzSSeU3tP9o9q
aliyun.AccessKey.Secret: Rn4nLhtz1se3LdtURifVIMHMM9yTAe